GET http://localhost:5000/api/people


###post new person and return that new person
POST http://localhost:5000/api/people
Content-Type: application/json

{
    "id": 5,
    "name": "Mbali"
}

###add new person and return a new list of people
POST http://localhost:5000/api/people/postman
Content-Type: application/json

{
    "id": 6,
    "name": "Mbali"
}

###Update person details
PUT http://localhost:5000/api/people/1
Content-Type: application/json

{
    "id": 1,
    "name": "Thulas Sweetie"
}

###Delete person
DELETE http://localhost:5000/api/people/1
Content-Type: application/json

{
   
}